using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using FinStream.Application.DTOs;
using FinStream.Application.Mappers;
using FinStream.Domain.Interfaces;

namespace FinStream.API.Controllers;

/// <summary>
/// This controller allows users to query the historical "Signals" (Alerts) 
/// that have been generated by our background Rule Engine.
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class SignalsController : ControllerBase
{
    private readonly ISignalRepository _signalRepository;
    private readonly IInstrumentRepository _instrumentRepository;

    public SignalsController(ISignalRepository signalRepository, IInstrumentRepository instrumentRepository)
    {
        _signalRepository = signalRepository;
        _instrumentRepository = instrumentRepository;
    }

    /// <summary>
    /// Gets a paginated list of all signals ever triggered.
    /// </summary>
    [HttpGet]
    [SwaggerOperation(
        Summary = "Get All Signals", 
        Description = "Retrieves a historical list of all trading signals triggered by the rule engine."
    )]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<SignalDto>>> GetAll(
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 50)
    {
        var signals = await _signalRepository.GetAllAsync(page, pageSize);
        return Ok(signals.Select(SignalMapper.ToDto));
    }

    /// <summary>
    /// Gets signals specific to a single instrument.
    /// </summary>
    [HttpGet("{symbol}")]
    [SwaggerOperation(
        Summary = "Get Signals By Symbol", 
        Description = "Retrieves a historical list of trading signals specifically for a given instrument (e.g., AAPL)."
    )]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<SignalDto>>> GetBySymbol(
        string symbol,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 50)
    {
        var instrument = await _instrumentRepository.GetBySymbolAsync(symbol);
        if (instrument == null) return NotFound(new { message = "Instrument not found" });

        var signals = await _signalRepository.GetByInstrumentAsync(instrument.Id, page, pageSize);
        return Ok(signals.Select(SignalMapper.ToDto));
    }
}